import type { QuestionCardQuestion } from '@/components/question/QuestionCard';

export type Question = QuestionCardQuestion;

export const questions: Question[] = [
  {
    id: 'jiejie-mathematics-1',
    topic: '質因數分解和短除法',
    type: 'basic',
    title: '質因數分解和短除法',
    instruction: '請選出正確的質因數分解。',
    question: '84 的質因數分解是哪一個？',
    options: ['2 × 2 × 3 × 7', '2 × 3 × 14', '4 × 21', '6 × 14'],
    answer: 0,
    hint: '先把 84 依序除以最小的質因數，直到每個因數都是質數。',
    explanation: '84 ÷ 2 = 42，42 ÷ 2 = 21，21 ÷ 3 = 7。最後得到的質因數是 2、2、3、7，所以 84 = 2 × 2 × 3 × 7。',
    encouragement: '答對了！你完成了質因數分解。',
  },
  {
    id: 'jiejie-mathematics-2',
    topic: '分數的除法',
    type: 'application',
    title: '分數的除法',
    instruction: '請計算分數除法。',
    question: '計算：3/4 ÷ 1/2 = ？',
    options: ['3/8', '2/3', '3/2', '1/4'],
    answer: 2,
    hint: '除以一個分數，可以改成乘以它的倒數。',
    explanation: '3/4 ÷ 1/2 = 3/4 × 2/1 = 6/4 = 3/2，也可以寫成 1 又 1/2。',
    encouragement: '答對了！你會計算分數的除法。',
  },
  {
    id: 'jiejie-mathematics-3',
    topic: '小數的除法',
    type: 'basic',
    title: '小數的除法',
    instruction: '請計算小數除法。',
    question: '計算：8.4 ÷ 0.7 = ？',
    options: ['1.2', '12', '120', '0.12'],
    answer: 1,
    hint: '把除數 0.7 變成整數時，被除數也要同時乘以 10。',
    explanation: '8.4 ÷ 0.7 的除數有一位小數，所以被除數和除數同時乘以 10，變成 84 ÷ 7。84 ÷ 7 = 12，因此 8.4 ÷ 0.7 = 12。',
    encouragement: '答對了！你能正確計算小數除法。',
  },
  {
    id: 'jiejie-mathematics-4',
    topic: '圓周長和圓面積',
    type: 'application',
    title: '圓面積',
    instruction: '請計算圓的面積。',
    question: '一個圓的半徑是 5 公分。若 π = 3.14，這個圓的面積是多少平方公分？',
    options: ['31.4 平方公分', '62.8 平方公分', '78.5 平方公分', '157 平方公分'],
    answer: 2,
    hint: '圓面積公式是 π × 半徑 × 半徑；題目已給半徑和 π。',
    explanation: '圓面積 = π × 半徑 × 半徑 = 3.14 × 5 × 5 = 3.14 × 25 = 78.5，所以面積是 78.5 平方公分。',
    encouragement: '答對了！你會使用圓面積公式。',
  },
  {
    id: 'jiejie-mathematics-5',
    topic: '比和比值',
    type: 'application',
    title: '比和比值',
    instruction: '請根據數量比解題。',
    question: '紅球和藍球的數量比是 2：3。若紅球有 8 顆，藍球有幾顆？',
    options: ['10 顆', '12 顆', '16 顆', '24 顆'],
    answer: 1,
    hint: '紅球的 2 份變成 8 顆，先找出 1 份是多少，再找 3 份。',
    explanation: '2 份紅球是 8 顆，所以 1 份是 8 ÷ 2 = 4 顆。藍球是 3 份，所以 4 × 3 = 12 顆。',
    encouragement: '答對了！你能用比來解決數量問題。',
  },
  {
    id: 'jiejie-mathematics-6',
    topic: '扇形的弧長和面積',
    type: 'application',
    title: '扇形弧長',
    instruction: '請計算扇形的弧長。',
    question: '一個圓心角 90° 的扇形，半徑為 6 公分。若 π = 3.14，這個扇形的弧長是多少公分？',
    options: ['6.28 公分', '9.42 公分', '18.84 公分', '37.68 公分'],
    answer: 1,
    hint: '圓心角 90° 的扇形弧長是整個圓周長的四分之一。',
    explanation: '整個圓周長 = 2 × 3.14 × 6 = 37.68 公分。圓心角 90° 的扇形弧長是整個圓周長的四分之一，所以 37.68 ÷ 4 = 9.42 公分。',
    encouragement: '答對了！你會計算扇形的弧長。',
  },
];
