import type { QuestionCardQuestion } from '@/components/question/QuestionCard';

export type Question = QuestionCardQuestion;

export const questions: Question[] = [
  {
    id: 'jiejie-chinese-1',
    reviewGroupId: 'jiejie-chinese-jiao-pronunciation',
    topic: '注音辨識',
    type: 'basic',
    title: '第一題',
    instruction: '請選出正確的注音。',
    question: '香蕉 的「蕉」讀音是？',
    options: ['① ㄐㄧㄠ', '② ㄑㄧㄠ', '③ ㄒㄧㄠ'],
    answer: 0,
    explanation: '「蕉」讀作 ㄐㄧㄠ。你已經掌握這個字的讀音！',
    encouragement: '🎉 答對了！',
  },
  {
    id: 'jiejie-chinese-2',
    reviewGroupId: 'jiejie-chinese-tian-radical',
    topic: '部首辨識',
    type: 'basic',
    title: '第二題',
    instruction: '請選出正確的部首。',
    question: '「天空」的「天」是什麼部首？',
    options: ['① 大', '② 一', '③ 人'],
    answer: 0,
    explanation: '「天」的部首是「大」。',
    encouragement: '🎉 答對了！',
  },
  {
    id: 'jiejie-chinese-3',
    reviewGroupId: 'jiejie-chinese-jiao-pronunciation',
    topic: '注音辨識',
    type: 'basic',
    title: '注音練習',
    instruction: '請選出正確的注音。',
    question: '校園裡有一棵芭蕉樹，「芭蕉」的「蕉」讀音是？',
    options: ['① ㄐㄧㄠ', '② ㄑㄧㄠ', '③ ㄒㄧㄠ'],
    answer: 0,
    explanation: '「蕉」不管出現在「香蕉」或「芭蕉」，都讀作「ㄐㄧㄠ」。',
    encouragement: '🎉 答對了！你會讀「蕉」了！',
  },
  {
    id: 'jiejie-chinese-4',
    reviewGroupId: 'jiejie-chinese-tian-radical',
    topic: '部首辨識',
    type: 'basic',
    title: '部首練習',
    instruction: '想查字典時，請選出要查的部首。',
    question: '想查「天」字時，應該查哪一個部首？',
    options: ['① 大部', '② 一部', '③ 人部'],
    answer: 0,
    explanation: '「天」的部首是「大」，所以查字典時要查「大部」。',
    encouragement: '🎉 答對了！你知道怎麼查「天」字了！',
  },
];
