import type { QuestionCardQuestion } from '@/components/question/QuestionCard';

export const questions: QuestionCardQuestion[] = [
  {
    id: 'meimei-chinese-1',
    reviewGroupId: 'meimei-chinese-gaoxing-meaning',
    topic: '詞語意思',
    type: 'basic',
    title: '詞語意思',
    instruction: '請選出和題目意思最接近的詞語。',
    question: '「高興」和下面哪一個詞語意思最接近？',
    options: ['快樂', '難過', '安靜'],
    answer: 0,
    explanation: '高興和快樂都表示心情很好。',
    encouragement: '答對了！你知道詞語的意思。',
  },
  {
    id: 'meimei-chinese-2',
    reviewGroupId: 'meimei-chinese-action-word-identification',
    topic: '動作詞辨識',
    type: 'application',
    title: '認識動作詞',
    instruction: '請找出句子中表示動作的詞語。',
    question: '「小明把書放在書包裡。」哪一個詞語表示動作？',
    options: ['小明', '放', '書包'],
    answer: 1,
    explanation: '「放」表示把東西放到一個地方的動作。',
    encouragement: '答對了！你找到動作詞了。',
  },
  {
    id: 'meimei-chinese-3',
    topic: '量詞運用',
    type: 'application',
    title: '量詞練習',
    instruction: '請選出最適合的量詞。',
    question: '一（　）鉛筆',
    options: ['本', '枝', '條'],
    answer: 1,
    explanation: '細長的鉛筆常用「枝」來計算。',
    encouragement: '答對了！量詞用得很正確。',
  },
  {
    id: 'meimei-chinese-4',
    reviewGroupId: 'meimei-chinese-gaoxing-meaning',
    topic: '詞語意思',
    type: 'basic',
    title: '詞語意思',
    instruction: '請根據句子的意思選出最適合的詞語。',
    question: '妹妹收到生日禮物，心裡很開心。下面哪一個詞語最適合形容妹妹的心情？',
    options: ['高興', '難過', '生氣'],
    answer: 0,
    explanation: '收到喜歡的生日禮物時，心情很開心，也可以說「很高興」。',
    encouragement: '答對了！你真的理解「高興」的意思了！',
  },
  {
    id: 'meimei-chinese-5',
    reviewGroupId: 'meimei-chinese-action-word-identification',
    topic: '動作詞辨識',
    type: 'application',
    title: '認識動作詞',
    instruction: '請找出句子中表示動作的詞語。',
    question: '「小狗在草地上跑。」哪一個詞語表示動作？',
    options: ['小狗', '草地', '跑'],
    answer: 2,
    explanation: '「跑」表示小狗正在做的動作。',
    encouragement: '答對了！你找到動作詞了。',
  },
  {
    id: 'meimei-chinese-6', topic: '詞語意思', type: 'basic', title: '詞語小偵探', instruction: '根據句子的意思，選出最接近「專心」的意思。', question: '上課時，小美「專心」聽老師說明，不和旁邊的同學聊天。「專心」是什麼意思？', options: ['心情很開心', '把心思集中在一件事情上', '動作非常快速', '一直想和別人說話'], answer: 1, hint: '想想小美為什麼沒有和旁邊的同學聊天。', explanation: '「專心」就是把注意力和心思集中在正在做的事情上。', encouragement: '答對了！你能從句子找到詞語的意思。',
  },
  {
    id: 'meimei-chinese-7', topic: '詞語意思', type: 'application', title: '從句子猜詞義', instruction: '閱讀情境，選出畫線詞語最適合的意思。', question: '弟弟第一次站上舞臺表演，看到臺下有這麼多人，他顯得十分「緊張」，兩隻手一直握得緊緊的。這裡的「緊張」最接近哪個意思？', options: ['因為擔心或害怕而心裡不安', '因為生氣而不想說話', '因為疲累而想睡覺', '因為高興而一直大笑'], answer: 0, hint: '注意「第一次上臺」、「很多人」和「手握得緊緊的」這些線索。', explanation: '從弟弟第一次上臺、看到很多觀眾，以及手握得緊緊的，可以知道這裡的「緊張」是因為擔心或害怕而感到不安。', encouragement: '很好！你會利用前後文來推測詞語的意思。',
  },
  {
    id: 'meimei-chinese-8', topic: '動作詞辨識', type: 'application', title: '選出正確的動作', instruction: '根據情境，選出最適合的動作詞。', question: '下課後，老師請小安把黑板上的字弄乾淨。小安拿起板擦，把黑板＿＿＿＿乾淨。', options: ['擦', '折', '踢', '捏'], answer: 0, hint: '想想板擦通常要怎麼使用。', explanation: '使用板擦把黑板上的字去除，最適合的動作詞是「擦」。', encouragement: '答對了！動作詞要和使用的物品搭配。',
  },
  {
    id: 'meimei-chinese-9', topic: '動作詞辨識', type: 'application', title: '哪個動作最適合', instruction: '根據句子的情境，選出最適合的動作詞。', question: '美術課時，老師請大家把黏土做成一顆圓圓的小球。小文把黏土放在手掌中輕輕地＿＿＿＿。', options: ['揉', '踩', '敲', '掃'], answer: 0, hint: '要讓柔軟的黏土慢慢變成圓球，需要用手反覆動作。', explanation: '「揉」是用手反覆搓動、按壓，很適合形容用手把黏土做成圓球的動作。', encouragement: '很棒！你能依照情境選出更精確的動作詞。',
  },
  {
    id: 'meimei-chinese-10', topic: '量詞運用', type: 'basic', title: '量詞配對', instruction: '選出最適合放入句子中的量詞。', question: '放學回家的路上，我看見一＿＿＿＿彩虹掛在天空中。', options: ['道', '顆', '本', '雙'], answer: 0, hint: '彩虹、光線等常使用同一個量詞。', explanation: '彩虹通常使用量詞「道」，所以應說「一道彩虹」。', encouragement: '答對了！你知道不同事物要搭配適合的量詞。',
  },
  {
    id: 'meimei-chinese-11', topic: '量詞運用', type: 'application', title: '量詞挑戰', instruction: '閱讀句子，選出量詞全部使用正確的選項。', question: '哪一句的量詞使用完全正確？', options: ['爸爸買了一「條」西瓜和兩「本」香蕉。', '桌上放著一「盞」檯燈和兩「本」故事書。', '池塘裡游著三「張」魚，旁邊開著一「頭」荷花。', '姐姐穿了一「把」外套，手上拿著一「雙」雨傘。'], answer: 1, hint: '一個一個檢查「檯燈」和「故事書」前面的量詞。', explanation: '「一盞檯燈」和「兩本故事書」的量詞都正確。其他選項中，西瓜、香蕉、魚、荷花、外套和雨傘的量詞都有不適合的地方。', encouragement: '太棒了！你能一次檢查兩個量詞是否使用正確。',
  },
];
