import type { QuestionCardQuestion } from '@/components/question/QuestionCard';

export const questions: QuestionCardQuestion[] = [
  {
    id: 'meimei-mathematics-1',
    topic: '數到 10000',
    type: 'basic',
    title: '位值分解',
    instruction: '請選出正確的位值分解。',
    question: '3407 的位值分解是哪一個？',
    options: ['3000 + 400 + 7', '3000 + 40 + 7', '300 + 400 + 7', '3000 + 400 + 70'],
    answer: 0,
    hint: '看千位、百位、十位和個位；3407 的十位有幾個？',
    explanation: '3407 有 3 個千、4 個百、0 個十和 7 個一，所以 3407 = 3000 + 400 + 7。',
    encouragement: '答對了！你會看數字的位值。',
  },
  {
    id: 'meimei-mathematics-2',
    topic: '四位數的加減',
    type: 'basic',
    title: '四位數的加法',
    instruction: '請計算四位數的加法。',
    question: '計算：3482 + 2157 = ？',
    options: ['5539', '5639', '5739', '5839'],
    answer: 1,
    hint: '可以從個位開始直式相加，滿十要進位。',
    explanation: '個位 2＋7＝9；十位 8＋5＝13，寫 3、向百位進 1；百位 4＋1＋1＝6；千位 3＋2＝5；所以答案為 5639。',
    encouragement: '答對了！你會正確完成四位數加法。',
  },
  {
    id: 'meimei-mathematics-3',
    topic: '乘法',
    type: 'basic',
    title: '乘法計算',
    instruction: '請計算乘法。',
    question: '計算：24 × 3 = ？',
    options: ['62', '72', '82', '92'],
    answer: 1,
    hint: '可以把 24 看成 20 和 4，再分別乘以 3。',
    explanation: '24 × 3 = (20 × 3) + (4 × 3) = 60 + 12 = 72。',
    encouragement: '答對了！你會用乘法計算。',
  },
  {
    id: 'meimei-mathematics-4',
    topic: '幾毫米',
    type: 'basic',
    title: '公分和毫米',
    instruction: '請進行公分和毫米的換算。',
    question: '3 公分 7 毫米等於幾毫米？',
    options: ['10 毫米', '30 毫米', '37 毫米', '307 毫米'],
    answer: 2,
    hint: '1 公分等於 10 毫米；先把 3 公分換成毫米，再加上 7 毫米。',
    explanation: '3 公分 = 3 × 10 = 30 毫米。再加上原本的 7 毫米，30 + 7 = 37 毫米。',
    encouragement: '答對了！你會進行長度單位換算。',
  },
  {
    id: 'meimei-mathematics-5',
    topic: '角、正方形和長方形',
    type: 'basic',
    title: '圖形的特徵',
    instruction: '請選出正確的圖形特徵。',
    question: '哪一個敘述正確？',
    options: ['正方形只有兩個直角。', '長方形的四條邊都一樣長。', '正方形的四條邊一樣長，而且四個角都是直角。', '長方形沒有直角。'],
    answer: 2,
    hint: '想一想正方形的邊和角各有什麼特徵。',
    explanation: '正方形有四條一樣長的邊，也有四個直角，所以第 3 個敘述正確。長方形也有四個直角，但不一定四邊都一樣長。',
    encouragement: '答對了！你能說出正方形的特徵。',
  },
  {
    id: 'meimei-mathematics-6',
    topic: '除法',
    type: 'application',
    title: '有餘數的除法',
    instruction: '請根據情境解決除法問題。',
    question: '26 顆糖果平分給 4 個人，每人分得幾顆？剩下幾顆？',
    options: ['6 顆，剩 2 顆', '6 顆，剩 4 顆', '7 顆，剩 2 顆', '7 顆，剩 0 顆'],
    answer: 0,
    hint: '找出 4 的乘法中最接近 26 且不超過 26 的數。',
    explanation: '4 × 6 = 24，26 - 24 = 2，所以每人分得 6 顆，還剩 2 顆。4 × 7 = 28，超過 26，不能分成每人 7 顆。',
    encouragement: '答對了！你會用除法處理分配問題。',
  },
  {
    id: 'meimei-mathematics-7',
    topic: '數到 10000',
    type: 'basic',
    title: '四位數大小比較',
    instruction: '請比較四位數的大小。',
    question: '下面哪一個數最大？',
    options: ['4070', '4700', '4077', '4007'],
    answer: 1,
    hint: '先比較千位，再比較百位。',
    explanation: '四個數的千位都為 4，接著比較百位；4700 的百位是 7，其他數的百位較小，所以 4700 最大。',
    encouragement: '答對了！你會比較四位數的大小。',
  },
  {
    id: 'meimei-mathematics-8',
    topic: '四位數的加減',
    type: 'basic',
    title: '四位數的減法',
    instruction: '請計算四位數的減法。',
    question: '計算：5000 − 2768 = ？',
    options: ['2132', '2232', '2332', '2432'],
    answer: 1,
    hint: '用直式從個位開始，遇到不夠減時要向前一位借 1。',
    explanation: '5000 − 2768：個位 10−8=2；十位借位後 9−6=3；百位借位後 9−7=2；千位 4−2=2，所以答案是 2232。',
    encouragement: '答對了！你會完成四位數退位減法。',
  },
  {
    id: 'meimei-mathematics-9',
    topic: '乘法',
    type: 'basic',
    title: '三位數乘一位數',
    instruction: '請計算乘法。',
    question: '計算：306 × 4 = ？',
    options: ['1024', '1124', '1224', '1324'],
    answer: 2,
    hint: '可以分成 300 × 4、0 × 4 和 6 × 4 再相加。',
    explanation: '306 × 4 = 300 × 4 + 0 × 4 + 6 × 4 = 1200 + 0 + 24 = 1224。',
    encouragement: '答對了！你會用位值分解完成乘法。',
  },
  {
    id: 'meimei-mathematics-10',
    topic: '幾毫米',
    type: 'application',
    title: '公分和毫米相加',
    instruction: '請計算長度的總和。',
    question: '一條彩帶長 6 公分 4 毫米，另一條長 2 公分 9 毫米，合起來長幾公分幾毫米？',
    options: ['8 公分 3 毫米', '8 公分 7 毫米', '9 公分 3 毫米', '9 公分 7 毫米'],
    answer: 2,
    hint: '先分別把公分和毫米相加；10 毫米可以換成 1 公分。',
    explanation: '公分：6+2=8；毫米：4+9=13 毫米，也就是 1 公分 3 毫米，所以總長是 9 公分 3 毫米。',
    encouragement: '答對了！你會計算公分和毫米的長度。',
  },
];
